// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensor.proto

/*
Package framework is a generated protocol buffer package.

It is generated from these files:
	tensor.proto

It has these top-level messages:
	TensorProto
	VariantTensorDataProto
*/
package framework

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import tensorflow2 "github.com/tensorflow/tensorflow/tensorflow/go/core/framework"
import tensorflow "github.com/tensorflow/tensorflow/tensorflow/go/core/framework"
import tensorflow1 "github.com/tensorflow/tensorflow/tensorflow/go/core/framework"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Protocol buffer representing a tensor.
type TensorProto struct {
	Dtype tensorflow1.DataType `protobuf:"varint,1,opt,name=dtype,enum=tensorflow.DataType" json:"dtype"`
	// Shape of the tensor.  TODO(touts): sort out the 0-rank issues.
	TensorShape *tensorflow.TensorShapeProto `protobuf:"bytes,2,opt,name=tensor_shape,json=tensorShape" json:"tensor_shape"`
	// Version number.
	//
	// In version 0, if the "repeated xxx" representations contain only one
	// element, that element is repeated to fill the shape.  This makes it easy
	// to represent a constant Tensor with a single value.
	VersionNumber int32 `protobuf:"varint,3,opt,name=version_number,json=versionNumber" json:"version_number"`
	// Serialized raw tensor content from either Tensor::AsProtoTensorContent or
	// memcpy in tensorflow::grpc::EncodeTensorToByteBuffer. This representation
	// can be used for all tensor types. The purpose of this representation is to
	// reduce serialization overhead during RPC call by avoiding serialization of
	// many repeated small items.
	TensorContent []byte `protobuf:"bytes,4,opt,name=tensor_content,json=tensorContent,proto3" json:"tensor_content"`
	// DT_HALF, DT_BFLOAT16. Note that since protobuf has no int16 type, we'll
	// have some pointless zero padding for each value here.
	HalfVal []int32 `protobuf:"varint,13,rep,packed,name=half_val,json=halfVal" json:"half_val"`
	// DT_FLOAT.
	FloatVal []float32 `protobuf:"fixed32,5,rep,packed,name=float_val,json=floatVal" json:"float_val"`
	// DT_DOUBLE.
	DoubleVal []float64 `protobuf:"fixed64,6,rep,packed,name=double_val,json=doubleVal" json:"double_val"`
	// DT_INT32, DT_INT16, DT_INT8, DT_UINT8.
	IntVal []int32 `protobuf:"varint,7,rep,packed,name=int_val,json=intVal" json:"int_val"`
	// DT_STRING
	StringVal [][]byte `protobuf:"bytes,8,rep,name=string_val,json=stringVal,proto3" json:"string_val"`
	// DT_COMPLEX64. scomplex_val(2*i) and scomplex_val(2*i+1) are real
	// and imaginary parts of i-th single precision complex.
	ScomplexVal []float32 `protobuf:"fixed32,9,rep,packed,name=scomplex_val,json=scomplexVal" json:"scomplex_val"`
	// DT_INT64
	Int64Val []int64 `protobuf:"varint,10,rep,packed,name=int64_val,json=int64Val" json:"int64_val"`
	// DT_BOOL
	BoolVal []bool `protobuf:"varint,11,rep,packed,name=bool_val,json=boolVal" json:"bool_val"`
	// DT_COMPLEX128. dcomplex_val(2*i) and dcomplex_val(2*i+1) are real
	// and imaginary parts of i-th double precision complex.
	DcomplexVal []float64 `protobuf:"fixed64,12,rep,packed,name=dcomplex_val,json=dcomplexVal" json:"dcomplex_val"`
	// DT_RESOURCE
	ResourceHandleVal []*tensorflow2.ResourceHandleProto `protobuf:"bytes,14,rep,name=resource_handle_val,json=resourceHandleVal" json:"resource_handle_val"`
	// DT_VARIANT
	VariantVal []*VariantTensorDataProto `protobuf:"bytes,15,rep,name=variant_val,json=variantVal" json:"variant_val"`
	// DT_UINT32
	Uint32Val []uint32 `protobuf:"varint,16,rep,packed,name=uint32_val,json=uint32Val" json:"uint32_val"`
	// DT_UINT64
	Uint64Val []uint64 `protobuf:"varint,17,rep,packed,name=uint64_val,json=uint64Val" json:"uint64_val"`
}

func (m *TensorProto) Reset()                    { *m = TensorProto{} }
func (m *TensorProto) String() string            { return proto.CompactTextString(m) }
func (*TensorProto) ProtoMessage()               {}
func (*TensorProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TensorProto) GetDtype() tensorflow1.DataType {
	if m != nil {
		return m.Dtype
	}
	return tensorflow1.DataType_DT_INVALID
}

func (m *TensorProto) GetTensorShape() *tensorflow.TensorShapeProto {
	if m != nil {
		return m.TensorShape
	}
	return nil
}

func (m *TensorProto) GetVersionNumber() int32 {
	if m != nil {
		return m.VersionNumber
	}
	return 0
}

func (m *TensorProto) GetTensorContent() []byte {
	if m != nil {
		return m.TensorContent
	}
	return nil
}

func (m *TensorProto) GetHalfVal() []int32 {
	if m != nil {
		return m.HalfVal
	}
	return nil
}

func (m *TensorProto) GetFloatVal() []float32 {
	if m != nil {
		return m.FloatVal
	}
	return nil
}

func (m *TensorProto) GetDoubleVal() []float64 {
	if m != nil {
		return m.DoubleVal
	}
	return nil
}

func (m *TensorProto) GetIntVal() []int32 {
	if m != nil {
		return m.IntVal
	}
	return nil
}

func (m *TensorProto) GetStringVal() [][]byte {
	if m != nil {
		return m.StringVal
	}
	return nil
}

func (m *TensorProto) GetScomplexVal() []float32 {
	if m != nil {
		return m.ScomplexVal
	}
	return nil
}

func (m *TensorProto) GetInt64Val() []int64 {
	if m != nil {
		return m.Int64Val
	}
	return nil
}

func (m *TensorProto) GetBoolVal() []bool {
	if m != nil {
		return m.BoolVal
	}
	return nil
}

func (m *TensorProto) GetDcomplexVal() []float64 {
	if m != nil {
		return m.DcomplexVal
	}
	return nil
}

func (m *TensorProto) GetResourceHandleVal() []*tensorflow2.ResourceHandleProto {
	if m != nil {
		return m.ResourceHandleVal
	}
	return nil
}

func (m *TensorProto) GetVariantVal() []*VariantTensorDataProto {
	if m != nil {
		return m.VariantVal
	}
	return nil
}

func (m *TensorProto) GetUint32Val() []uint32 {
	if m != nil {
		return m.Uint32Val
	}
	return nil
}

func (m *TensorProto) GetUint64Val() []uint64 {
	if m != nil {
		return m.Uint64Val
	}
	return nil
}

// Protocol buffer representing the serialization format of DT_VARIANT tensors.
type VariantTensorDataProto struct {
	// Name of the type of objects being serialized.
	TypeName string `protobuf:"bytes,1,opt,name=type_name,json=typeName" json:"type_name"`
	// Portions of the object that are not Tensors.
	Metadata []byte `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata"`
	// Tensors contained within objects being serialized.
	Tensors []*TensorProto `protobuf:"bytes,3,rep,name=tensors" json:"tensors"`
}

func (m *VariantTensorDataProto) Reset()                    { *m = VariantTensorDataProto{} }
func (m *VariantTensorDataProto) String() string            { return proto.CompactTextString(m) }
func (*VariantTensorDataProto) ProtoMessage()               {}
func (*VariantTensorDataProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *VariantTensorDataProto) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *VariantTensorDataProto) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *VariantTensorDataProto) GetTensors() []*TensorProto {
	if m != nil {
		return m.Tensors
	}
	return nil
}

func init() {
	proto.RegisterType((*TensorProto)(nil), "tensorflow.TensorProto")
	proto.RegisterType((*VariantTensorDataProto)(nil), "tensorflow.VariantTensorDataProto")
}

func init() { proto.RegisterFile("tensor.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 550 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x3d, 0x6f, 0xdb, 0x30,
	0x10, 0x86, 0xa1, 0x30, 0x8e, 0x25, 0x4a, 0x76, 0x13, 0xf5, 0x4b, 0x70, 0x1a, 0x84, 0x35, 0x10,
	0x80, 0xe8, 0x60, 0xa3, 0x4e, 0xd1, 0xad, 0x28, 0xe0, 0x74, 0xe8, 0x94, 0x06, 0x6a, 0x90, 0xa1,
	0x8b, 0x41, 0x5b, 0xb4, 0x2d, 0x54, 0x22, 0x0d, 0x8a, 0x76, 0x9a, 0xbd, 0x7f, 0xb0, 0xff, 0xa6,
	0x63, 0xc1, 0x3b, 0xd9, 0x56, 0xbf, 0x36, 0xf1, 0xbd, 0xe7, 0xde, 0xe3, 0xf1, 0x4e, 0x34, 0xb2,
	0x52, 0x55, 0xda, 0x0c, 0x56, 0x46, 0x5b, 0x1d, 0x53, 0x3c, 0xcd, 0x0b, 0x7d, 0xdf, 0x7b, 0x6a,
	0x64, 0xa5, 0xd7, 0x66, 0x26, 0x27, 0x4b, 0xa1, 0xb2, 0x42, 0x22, 0xd2, 0x8b, 0x11, 0x99, 0x54,
	0x4b, 0xb1, 0xda, 0x6a, 0xa1, 0x7d, 0x58, 0xc9, 0x0a, 0x0f, 0xfd, 0x1f, 0x2d, 0x1a, 0xde, 0x02,
	0x73, 0x03, 0x9e, 0xaf, 0x68, 0x2b, 0x73, 0xf1, 0xc4, 0x63, 0x1e, 0xef, 0x8e, 0x9e, 0x0c, 0xf6,
	0x35, 0x06, 0x1f, 0x84, 0x15, 0xb7, 0x0f, 0x2b, 0x99, 0x22, 0x12, 0xbf, 0xdf, 0xde, 0x07, 0xed,
	0x93, 0x03, 0xe6, 0xf1, 0x70, 0xf4, 0xa2, 0x99, 0x82, 0xd6, 0x9f, 0x5d, 0x18, 0xfc, 0xd3, 0xd0,
	0xee, 0x95, 0xf8, 0x82, 0x76, 0x37, 0xd2, 0x54, 0xb9, 0x56, 0x13, 0xb5, 0x2e, 0xa7, 0xd2, 0x24,
	0x84, 0x79, 0xbc, 0x95, 0x76, 0x6a, 0xf5, 0x1a, 0x44, 0x87, 0xd5, 0x75, 0x66, 0x5a, 0x59, 0xa9,
	0x6c, 0x72, 0xc8, 0x3c, 0x1e, 0xa5, 0x1d, 0x54, 0xaf, 0x50, 0x8c, 0xcf, 0xa8, 0xbf, 0x14, 0xc5,
	0x7c, 0xb2, 0x11, 0x45, 0xd2, 0x61, 0x84, 0xb7, 0xc6, 0x07, 0xc7, 0x5e, 0xda, 0x76, 0xda, 0x9d,
	0x28, 0xe2, 0x73, 0x1a, 0xcc, 0x0b, 0x2d, 0x2c, 0xc4, 0x5b, 0x8c, 0xf0, 0x03, 0x88, 0xfb, 0x20,
	0x3a, 0xe0, 0x25, 0xa5, 0x99, 0x5e, 0x4f, 0x0b, 0x09, 0xc4, 0x11, 0x23, 0xdc, 0x03, 0x22, 0x40,
	0xd5, 0x21, 0xa7, 0xb4, 0x9d, 0x2b, 0x74, 0x68, 0xef, 0x2a, 0x1c, 0xe5, 0x0a, 0xf2, 0xcf, 0x28,
	0xad, 0xac, 0xc9, 0xd5, 0x02, 0xe2, 0x3e, 0x23, 0x3c, 0x4a, 0x03, 0x54, 0x5c, 0xf8, 0x82, 0x46,
	0xd5, 0x4c, 0x97, 0xab, 0x42, 0x7e, 0x03, 0x20, 0xd8, 0x5d, 0x21, 0xdc, 0xea, 0xf5, 0x35, 0x73,
	0x65, 0xdf, 0xbe, 0x01, 0x86, 0x32, 0xc2, 0x09, 0x5e, 0x13, 0x44, 0x2c, 0xe3, 0x4f, 0xb5, 0x2e,
	0x20, 0x1e, 0x32, 0xc2, 0x7d, 0x6c, 0xd3, 0x69, 0x75, 0x99, 0xac, 0x59, 0x26, 0xda, 0xf5, 0x11,
	0x66, 0x8d, 0x32, 0x9f, 0xe8, 0xe3, 0x3f, 0x36, 0x06, 0xe8, 0x2e, 0x23, 0x3c, 0x1c, 0x9d, 0x37,
	0x47, 0x98, 0xd6, 0xd8, 0x47, 0xa0, 0x70, 0x8a, 0x27, 0xe6, 0x37, 0xd1, 0x19, 0x5e, 0xd1, 0x70,
	0x23, 0x4c, 0x2e, 0xea, 0xe7, 0x79, 0x04, 0x46, 0xfd, 0xa6, 0xd1, 0x1d, 0x86, 0x71, 0x25, 0xdc,
	0x2e, 0xa1, 0x17, 0xad, 0xd3, 0xea, 0x11, 0xac, 0x73, 0x65, 0x2f, 0x47, 0xe0, 0x71, 0xcc, 0x08,
	0xef, 0xe0, 0x08, 0x50, 0x6d, 0x20, 0xf5, 0x03, 0x9d, 0x30, 0xc2, 0x0f, 0xf7, 0x08, 0xbc, 0x50,
	0xff, 0xbb, 0x47, 0x9f, 0xfd, 0xbb, 0x58, 0x7c, 0x4a, 0x03, 0xb7, 0xba, 0x13, 0x25, 0x4a, 0x5c,
	0xf1, 0x20, 0xf5, 0x9d, 0x70, 0x2d, 0x4a, 0x19, 0xf7, 0xa8, 0x5f, 0x4a, 0x2b, 0x32, 0x61, 0x05,
	0xec, 0x72, 0x94, 0xee, 0xce, 0xf1, 0x6b, 0xda, 0xc6, 0x56, 0xaa, 0x84, 0x40, 0x6b, 0xcf, 0xff,
	0x5e, 0x73, 0xec, 0x67, 0xcb, 0x8d, 0x0b, 0x9a, 0x68, 0xb3, 0x68, 0x62, 0x73, 0x23, 0x4a, 0x79,
	0xaf, 0xcd, 0xd7, 0x71, 0xd4, 0xc8, 0xa8, 0x6e, 0xbc, 0x2f, 0xef, 0x16, 0xb9, 0x5d, 0xae, 0xa7,
	0x83, 0x99, 0x2e, 0x87, 0xfb, 0x84, 0xff, 0x7c, 0x2e, 0xf4, 0x70, 0xa6, 0x8d, 0x1c, 0xee, 0xec,
	0x7e, 0x7a, 0xde, 0xf4, 0x08, 0xfe, 0xe7, 0xcb, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x13, 0xdf,
	0x90, 0x36, 0x23, 0x04, 0x00, 0x00,
}
