// Code generated by protoc-gen-go. DO NOT EDIT.
// source: classification.proto

/*
Package tensorflow_s is a generated protocol buffer package.

It is generated from these files:
	classification.proto
	example.proto
	feature.proto
	input.proto
	model.proto
	predict.proto
	prediction_service.proto
	regression.proto
	resource_handle.proto
	tensor.proto
	tensor_shape.proto
	types.proto

It has these top-level messages:
	Class
	Classifications
	ClassificationResult
	ClassificationRequest
	ClassificationResponse
	Example
	SequenceExample
	BytesList
	FloatList
	Int64List
	Feature
	Features
	FeatureList
	FeatureLists
	ExampleList
	ExampleListWithContext
	Input
	ModelSpec
	PredictRequest
	PredictResponse
	Regression
	RegressionResult
	RegressionRequest
	RegressionResponse
	ResourceHandleProto
	TensorProto
	VariantTensorDataProto
	TensorShapeProto
*/
package tensorflow_s

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A single class.
type Class struct {
	// Label or name of the class.
	Label string `protobuf:"bytes,1,opt,name=label" json:"label"`
	// Score for this class (e.g., the probability the item belongs to this
	// class). As per the proto3 default-value semantics, if the score is missing,
	// it should be treated as 0.
	Score float32 `protobuf:"fixed32,2,opt,name=score" json:"score"`
}

func (m *Class) Reset()                    { *m = Class{} }
func (m *Class) String() string            { return proto.CompactTextString(m) }
func (*Class) ProtoMessage()               {}
func (*Class) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Class) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Class) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

// List of classes for a single item (tensorflow.Example).
type Classifications struct {
	Classes []*Class `protobuf:"bytes,1,rep,name=classes" json:"classes"`
}

func (m *Classifications) Reset()                    { *m = Classifications{} }
func (m *Classifications) String() string            { return proto.CompactTextString(m) }
func (*Classifications) ProtoMessage()               {}
func (*Classifications) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Classifications) GetClasses() []*Class {
	if m != nil {
		return m.Classes
	}
	return nil
}

// Contains one result per input example, in the same order as the input in
// ClassificationRequest.
type ClassificationResult struct {
	Classifications []*Classifications `protobuf:"bytes,1,rep,name=classifications" json:"classifications"`
}

func (m *ClassificationResult) Reset()                    { *m = ClassificationResult{} }
func (m *ClassificationResult) String() string            { return proto.CompactTextString(m) }
func (*ClassificationResult) ProtoMessage()               {}
func (*ClassificationResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ClassificationResult) GetClassifications() []*Classifications {
	if m != nil {
		return m.Classifications
	}
	return nil
}

type ClassificationRequest struct {
	// Model Specification. If version is not specified, will use the latest
	// (numerical) version.
	ModelSpec *ModelSpec `protobuf:"bytes,1,opt,name=model_spec,json=modelSpec" json:"model_spec"`
	// Input data.
	Input *Input `protobuf:"bytes,2,opt,name=input" json:"input"`
}

func (m *ClassificationRequest) Reset()                    { *m = ClassificationRequest{} }
func (m *ClassificationRequest) String() string            { return proto.CompactTextString(m) }
func (*ClassificationRequest) ProtoMessage()               {}
func (*ClassificationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ClassificationRequest) GetModelSpec() *ModelSpec {
	if m != nil {
		return m.ModelSpec
	}
	return nil
}

func (m *ClassificationRequest) GetInput() *Input {
	if m != nil {
		return m.Input
	}
	return nil
}

type ClassificationResponse struct {
	// Effective Model Specification used for classification.
	ModelSpec *ModelSpec `protobuf:"bytes,2,opt,name=model_spec,json=modelSpec" json:"model_spec"`
	// Result of the classification.
	Result *ClassificationResult `protobuf:"bytes,1,opt,name=result" json:"result"`
}

func (m *ClassificationResponse) Reset()                    { *m = ClassificationResponse{} }
func (m *ClassificationResponse) String() string            { return proto.CompactTextString(m) }
func (*ClassificationResponse) ProtoMessage()               {}
func (*ClassificationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ClassificationResponse) GetModelSpec() *ModelSpec {
	if m != nil {
		return m.ModelSpec
	}
	return nil
}

func (m *ClassificationResponse) GetResult() *ClassificationResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Class)(nil), "tensorflow_s.serving.Class")
	proto.RegisterType((*Classifications)(nil), "tensorflow_s.serving.Classifications")
	proto.RegisterType((*ClassificationResult)(nil), "tensorflow_s.serving.ClassificationResult")
	proto.RegisterType((*ClassificationRequest)(nil), "tensorflow_s.serving.ClassificationRequest")
	proto.RegisterType((*ClassificationResponse)(nil), "tensorflow_s.serving.ClassificationResponse")
}

func init() { proto.RegisterFile("classification.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x65, 0x23, 0xa9, 0x74, 0x72, 0x28, 0x2c, 0x51, 0x43, 0x3d, 0x18, 0x02, 0x42, 0xf0, 0x10,
	0xb1, 0xc5, 0xab, 0x87, 0xf6, 0xa2, 0x07, 0x11, 0xd6, 0x9b, 0x97, 0x92, 0xc6, 0x69, 0x09, 0x6c,
	0xb3, 0x31, 0xb3, 0xd1, 0x7f, 0xf0, 0x1b, 0xfc, 0x50, 0x8f, 0x92, 0xdd, 0x06, 0x4d, 0xac, 0xa2,
	0xb7, 0x9d, 0xe1, 0xbd, 0x37, 0xef, 0x3d, 0x16, 0xfc, 0x4c, 0xa6, 0x44, 0xf9, 0x2a, 0xcf, 0x52,
	0x9d, 0xab, 0x22, 0x29, 0x2b, 0xa5, 0x15, 0xf7, 0x35, 0x16, 0xa4, 0xaa, 0x95, 0x54, 0x2f, 0x0b,
	0x4a, 0x08, 0xab, 0xe7, 0xbc, 0x58, 0x8f, 0xbd, 0xbc, 0x28, 0x6b, 0x6d, 0x21, 0x63, 0x6f, 0xa3,
	0x1e, 0x51, 0xda, 0x21, 0x9a, 0x82, 0x3b, 0x6f, 0x74, 0xb8, 0x0f, 0xae, 0x4c, 0x97, 0x28, 0x03,
	0x16, 0xb2, 0x78, 0x28, 0xec, 0xd0, 0x6c, 0x29, 0x53, 0x15, 0x06, 0x4e, 0xc8, 0x62, 0x47, 0xd8,
	0x21, 0xba, 0x86, 0xd1, 0xbc, 0x73, 0x9c, 0xf8, 0x25, 0xec, 0x1b, 0x3f, 0x48, 0x01, 0x0b, 0xf7,
	0x62, 0x6f, 0x72, 0x9c, 0xec, 0x72, 0x92, 0x18, 0x9e, 0x68, 0xb1, 0xd1, 0x1a, 0xfc, 0xae, 0x92,
	0x40, 0xaa, 0xa5, 0xe6, 0x77, 0x30, 0xea, 0xc6, 0x6b, 0x65, 0x4f, 0x7f, 0x91, 0xfd, 0x04, 0x8b,
	0x3e, 0x3b, 0x7a, 0x65, 0x70, 0xd0, 0xbf, 0xf4, 0x54, 0x23, 0x69, 0x7e, 0x05, 0x60, 0x0a, 0x59,
	0x50, 0x89, 0x99, 0x49, 0xef, 0x4d, 0x4e, 0x76, 0x5f, 0xb9, 0x6d, 0x70, 0xf7, 0x25, 0x66, 0x62,
	0xb8, 0x69, 0x9f, 0xfc, 0x02, 0x5c, 0xd3, 0xae, 0xa9, 0xe8, 0xc7, 0xdc, 0x37, 0x0d, 0x44, 0x58,
	0x64, 0xf4, 0xc6, 0xe0, 0xf0, 0x5b, 0xec, 0x52, 0x15, 0x84, 0x3d, 0x37, 0xce, 0xbf, 0xdd, 0xcc,
	0x60, 0x50, 0x99, 0x0a, 0xb7, 0x49, 0xce, 0xfe, 0xd2, 0x97, 0x2d, 0x5d, 0x6c, 0x99, 0xb3, 0xa3,
	0x07, 0x6e, 0x3e, 0xc7, 0xf9, 0x57, 0xea, 0x3b, 0x63, 0xcb, 0x81, 0x59, 0x4f, 0x3f, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x78, 0x6f, 0x59, 0x26, 0x7b, 0x02, 0x00, 0x00,
}
