// Code generated by protoc-gen-go. DO NOT EDIT.
// source: regression.proto

package tensorflow_s

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Regression result for a single item (tensorflow.Example).
type Regression struct {
	Value float32 `protobuf:"fixed32,1,opt,name=value" json:"value"`
}

func (m *Regression) Reset()                    { *m = Regression{} }
func (m *Regression) String() string            { return proto.CompactTextString(m) }
func (*Regression) ProtoMessage()               {}
func (*Regression) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

func (m *Regression) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

// Contains one result per input example, in the same order as the input in
// RegressionRequest.
type RegressionResult struct {
	Regressions []*Regression `protobuf:"bytes,1,rep,name=regressions" json:"regressions"`
}

func (m *RegressionResult) Reset()                    { *m = RegressionResult{} }
func (m *RegressionResult) String() string            { return proto.CompactTextString(m) }
func (*RegressionResult) ProtoMessage()               {}
func (*RegressionResult) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{1} }

func (m *RegressionResult) GetRegressions() []*Regression {
	if m != nil {
		return m.Regressions
	}
	return nil
}

type RegressionRequest struct {
	// Model Specification. If version is not specified, will use the latest
	// (numerical) version.
	ModelSpec *ModelSpec `protobuf:"bytes,1,opt,name=model_spec,json=modelSpec" json:"model_spec"`
	// Input data.
	Input *Input `protobuf:"bytes,2,opt,name=input" json:"input"`
}

func (m *RegressionRequest) Reset()                    { *m = RegressionRequest{} }
func (m *RegressionRequest) String() string            { return proto.CompactTextString(m) }
func (*RegressionRequest) ProtoMessage()               {}
func (*RegressionRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{2} }

func (m *RegressionRequest) GetModelSpec() *ModelSpec {
	if m != nil {
		return m.ModelSpec
	}
	return nil
}

func (m *RegressionRequest) GetInput() *Input {
	if m != nil {
		return m.Input
	}
	return nil
}

type RegressionResponse struct {
	// Effective Model Specification used for regression.
	ModelSpec *ModelSpec        `protobuf:"bytes,2,opt,name=model_spec,json=modelSpec" json:"model_spec"`
	Result    *RegressionResult `protobuf:"bytes,1,opt,name=result" json:"result"`
}

func (m *RegressionResponse) Reset()                    { *m = RegressionResponse{} }
func (m *RegressionResponse) String() string            { return proto.CompactTextString(m) }
func (*RegressionResponse) ProtoMessage()               {}
func (*RegressionResponse) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{3} }

func (m *RegressionResponse) GetModelSpec() *ModelSpec {
	if m != nil {
		return m.ModelSpec
	}
	return nil
}

func (m *RegressionResponse) GetResult() *RegressionResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Regression)(nil), "tensorflow_s.serving.Regression")
	proto.RegisterType((*RegressionResult)(nil), "tensorflow_s.serving.RegressionResult")
	proto.RegisterType((*RegressionRequest)(nil), "tensorflow_s.serving.RegressionRequest")
	proto.RegisterType((*RegressionResponse)(nil), "tensorflow_s.serving.RegressionResponse")
}

func init() { proto.RegisterFile("regression.proto", fileDescriptor7) }

var fileDescriptor7 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x4a, 0x4d, 0x2f,
	0x4a, 0x2d, 0x2e, 0xce, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x29, 0x49,
	0xcd, 0x2b, 0xce, 0x2f, 0x4a, 0xcb, 0xc9, 0x2f, 0x8f, 0x2f, 0xd6, 0x2b, 0x4e, 0x2d, 0x2a, 0xcb,
	0xcc, 0x4b, 0x97, 0xe2, 0xce, 0xcc, 0x2b, 0x28, 0x2d, 0x81, 0x28, 0x91, 0xe2, 0xce, 0xcd, 0x4f,
	0x49, 0xcd, 0x81, 0x70, 0x94, 0x94, 0xb8, 0xb8, 0x82, 0xe0, 0x66, 0x08, 0x89, 0x70, 0xb1, 0x96,
	0x25, 0xe6, 0x94, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x05, 0x41, 0x38, 0x4a, 0x61, 0x5c,
	0x02, 0x08, 0x35, 0x41, 0xa9, 0xc5, 0xa5, 0x39, 0x25, 0x42, 0x4e, 0x5c, 0xdc, 0x08, 0xbb, 0x8b,
	0x25, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x14, 0xf4, 0xb0, 0xd9, 0xae, 0x87, 0xa4, 0x19, 0x59,
	0x93, 0x52, 0x1b, 0x23, 0x97, 0x20, 0xb2, 0xc1, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x76, 0x5c,
	0x5c, 0x60, 0x07, 0xc6, 0x17, 0x17, 0xa4, 0x26, 0x83, 0x1d, 0xc2, 0x6d, 0x24, 0x8f, 0xdd, 0x60,
	0x5f, 0x90, 0xba, 0xe0, 0x82, 0xd4, 0xe4, 0x20, 0xce, 0x5c, 0x18, 0x53, 0xc8, 0x90, 0x8b, 0x15,
	0xec, 0x5b, 0x09, 0x26, 0xb0, 0x56, 0x69, 0xec, 0x5a, 0x3d, 0x41, 0x4a, 0x82, 0x20, 0x2a, 0x95,
	0xa6, 0x30, 0x72, 0x09, 0xa1, 0xf8, 0xb0, 0x20, 0x3f, 0xaf, 0x38, 0x15, 0xcd, 0x25, 0x4c, 0x24,
	0xbb, 0xc4, 0x8e, 0x8b, 0xad, 0x08, 0x1c, 0x5a, 0x50, 0x5f, 0xa8, 0x11, 0x0c, 0x1e, 0xb0, 0xea,
	0x20, 0xa8, 0x2e, 0x27, 0xf1, 0x28, 0x21, 0x70, 0x24, 0xe9, 0x23, 0x6b, 0xfb, 0xc1, 0xc8, 0x98,
	0xc4, 0x06, 0x16, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x81, 0x17, 0x8f, 0x5c, 0xff, 0x01,
	0x00, 0x00,
}
