// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensor_shape.proto

package tensorflow_s

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Dimensions of a tensor.
type TensorShapeProto struct {
	// Dimensions of the tensor, such as {"input", 30}, {"output", 40}
	// for a 30 x 40 2D tensor.  If an entry has size -1, this
	// corresponds to a dimension of unknown size. The names are
	// optional.
	//
	// The order of entries in "dim" matters: It indicates the layout of the
	// values in the tensor in-memory representation.
	//
	// The first entry in "dim" is the outermost dimension used to layout the
	// values, the last entry is the innermost dimension.  This matches the
	// in-memory layout of RowMajor Eigen tensors.
	//
	// If "dim.size()" > 0, "unknown_rank" must be false.
	Dim []*TensorShapeProto_Dim `protobuf:"bytes,2,rep,name=dim" json:"dim"`
	// If true, the number of dimensions in the shape is unknown.
	//
	// If true, "dim.size()" must be 0.
	UnknownRank bool `protobuf:"varint,3,opt,name=unknown_rank,json=unknownRank" json:"unknown_rank"`
}

func (m *TensorShapeProto) Reset()                    { *m = TensorShapeProto{} }
func (m *TensorShapeProto) String() string            { return proto.CompactTextString(m) }
func (*TensorShapeProto) ProtoMessage()               {}
func (*TensorShapeProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{0} }

func (m *TensorShapeProto) GetDim() []*TensorShapeProto_Dim {
	if m != nil {
		return m.Dim
	}
	return nil
}

func (m *TensorShapeProto) GetUnknownRank() bool {
	if m != nil {
		return m.UnknownRank
	}
	return false
}

// One dimension of the tensor.
type TensorShapeProto_Dim struct {
	// Size of the tensor in that dimension.
	// This value must be >= -1, but values of -1 are reserved for "unknown"
	// shapes (values of -1 mean "unknown" dimension).  Certain wrappers
	// that work with TensorShapeProto may fail at runtime when deserializing
	// a TensorShapeProto containing a dim value of -1.
	Size int64 `protobuf:"varint,1,opt,name=size" json:"size"`
	// Optional name of the tensor dimension.
	Name string `protobuf:"bytes,2,opt,name=name" json:"name"`
}

func (m *TensorShapeProto_Dim) Reset()                    { *m = TensorShapeProto_Dim{} }
func (m *TensorShapeProto_Dim) String() string            { return proto.CompactTextString(m) }
func (*TensorShapeProto_Dim) ProtoMessage()               {}
func (*TensorShapeProto_Dim) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{0, 0} }

func (m *TensorShapeProto_Dim) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *TensorShapeProto_Dim) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*TensorShapeProto)(nil), "tensorflow_s.TensorShapeProto")
	proto.RegisterType((*TensorShapeProto_Dim)(nil), "tensorflow_s.TensorShapeProto.Dim")
}

func init() { proto.RegisterFile("tensor_shape.proto", fileDescriptor10) }

var fileDescriptor10 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x49, 0xcd, 0x2b,
	0xce, 0x2f, 0x8a, 0x2f, 0xce, 0x48, 0x2c, 0x48, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x81, 0x88, 0xa5, 0xe5, 0xe4, 0x97, 0xc7, 0x17, 0x2b, 0xcd, 0x62, 0xe4, 0x12, 0x08, 0x01, 0x0b,
	0x04, 0x83, 0xd4, 0x04, 0x80, 0x95, 0x98, 0x70, 0x31, 0xa7, 0x64, 0xe6, 0x4a, 0x30, 0x29, 0x30,
	0x6b, 0x70, 0x1b, 0x29, 0xe9, 0x21, 0x6b, 0xd0, 0x43, 0x57, 0xac, 0xe7, 0x92, 0x99, 0x1b, 0x04,
	0x52, 0x2e, 0xa4, 0xc8, 0xc5, 0x53, 0x9a, 0x97, 0x9d, 0x97, 0x5f, 0x9e, 0x17, 0x5f, 0x94, 0x98,
	0x97, 0x2d, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x11, 0xc4, 0x0d, 0x15, 0x0b, 0x4a, 0xcc, 0xcb, 0x96,
	0xd2, 0xe5, 0x62, 0x76, 0xc9, 0xcc, 0x15, 0x12, 0xe2, 0x62, 0x29, 0xce, 0xac, 0x4a, 0x95, 0x60,
	0x54, 0x60, 0xd4, 0x60, 0x0e, 0x02, 0xb3, 0x41, 0x62, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x93, 0x1b, 0x97, 0x44, 0x7e, 0x51, 0x3a, 0x92, 0xfd, 0x7a,
	0x69, 0x45, 0x89, 0xb9, 0xa9, 0xe5, 0xf9, 0x45, 0xd9, 0x4e, 0x82, 0xe8, 0x0e, 0x29, 0x0e, 0x60,
	0x8c, 0x12, 0x02, 0x7b, 0x51, 0x1f, 0xd9, 0xc1, 0x3f, 0x18, 0x19, 0x93, 0xd8, 0xc0, 0xc2, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaa, 0xd5, 0x10, 0xa2, 0x0f, 0x01, 0x00, 0x00,
}
